name: Build code
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: install dependencies
      run: make install
    - name: Lint
      run: make lint
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"
