name: Build code
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check environment
      run: |
        pwd
        ls -lA
    - name: Lint
      run: make fix
